### ISSUE TITLE
Channels are not supported when viewing a projects dashboard

### ISSUE THREAD

**Issue by BobJWalker** [OctopusSolutionsEngineering/OctopusCopilot#13]
### Octopus version

2024.3.8245 (Cloud)

### What happened

My project dashboard is this:

![image](https://github.com/user-attachments/assets/9f2ca632-623b-4a87-958f-dabf3d3d7d8c)

The extension shows this:
![image](https://github.com/user-attachments/assets/cafc7839-7e49-4257-93a3-3b292f86e3b0)

### Chat query

Show me the dashboard for the project [project name]

### Chat output

![image](https://github.com/user-attachments/assets/5d2bd7ea-d14d-4d51-9048-f22c5b7426a3)

### Reproduction steps

Add channels to your project.

**Comment by harrisonmeister** [comment]
This should now be _partially_ resolved:

Note: Channels will now show for an **untenanted project only**.

Still to come: Adding support to selectively choose the channel you wish to see the dashboard for

**Comment by BobJWalker** [comment]
The latest push doesn't look quite right when I push a release all the way to Prod.  

My dashboard:
![image](https://github.com/user-attachments/assets/f100f646-3aeb-468a-9574-52656438037a)

The CoPilot Extension Dashboard.  I'd expect release 1.0.30 to be the only one release visible the release channel, but I can see two older releases.
![image](https://github.com/user-attachments/assets/7e0e3652-70bc-4c22-a81f-337e29850062)

**Comment by harrisonmeister** [comment]
This is resolved by https://github.com/OctopusSolutionsEngineering/OctopusCopilot/commit/3bd73dbde411aa1ae5da550f6db2692ea59fc1fb

Note: Although you previously may only have seen one release per channel (in each environment), the summary did support multiple releases, but they weren't showing correctly. Now that's fixed, multiple releases may be displayed - this mirrors the behavior of the project dashboard. If you have a lot of highlights in your deployment, this could lead to a large table being displayed.
