### ISSUE TITLE
Approve / Reject Manual Interventions

### ISSUE THREAD

**Issue by BobJWalker** [OctopusSolutionsEngineering/OctopusCopilot#14]
### Chat query

Support for manual interventions

Query 1: Approve [release number] to [environment name] for [project name] in [space name]
Query 2: Reject [release number] to [environment name] for [project name] in [space name]

### Action

Approve or reject a manual intervention in the deployment.  

Ideally, the prompt would also show me who has permissions to approve or reject if my user does not.

**Comment by harrisonmeister** [comment]
For displaying the team names who have permissions for approve / reject:

The object the manual intervention returns has the following parameters:
IsPending - it is a pending manual intervention
CanTakeResponsibility - The user associated with the API key can approve it.
ResponsibleTeamIds - The list of team IDs who has permissions to approve it.
