### ISSUE TITLE
Cannot run a runbook

### ISSUE THREAD

**Issue by BobJWalker** [OctopusSolutionsEngineering/OctopusCopilot#18]
### Octopus version

2024.3.xxxx

### What happened

I have set the default project to "TridentAI" and the default space to "Default."

I run the command to run a runbook, but I'm told the environment isn't supported
![image](https://github.com/user-attachments/assets/7ba9d9f6-a385-4b25-a371-e4d62154b0f7)

However that environment clearly is supported
![image](https://github.com/user-attachments/assets/2c55a3c6-86e1-4c3c-ae8f-75c17f10c3f5)

### Chat query

See above

### Chat output

See above

### Reproduction steps

See above

**Comment by harrisonmeister** [comment]
@BobJWalker what does the runbook settings look like for environments?

Is it by any chance all environments?

**Comment by BobJWalker** [comment]
I tried both all environments and lifecycle environments.  
![image](https://github.com/user-attachments/assets/2653b8fc-3c82-44ea-b3b4-3c8bad15b21f)

**Comment by harrisonmeister** [comment]
I think the middle option eg only specific environments is the one that works currently. Should be an easy fix to support the other two though

**Comment by harrisonmeister** [comment]
Fixed by https://github.com/OctopusSolutionsEngineering/OctopusCopilot/commit/61d0631c60352bfe311f36115e030a310e6e3936
