### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by mcasperson** [OctopusSolutionsEngineering/OctopusCopilot#6]
### Chat query

- Create a new release for project "My Project" with version "1.2.3.4"
- Create a new release for project "My Project" with version "1.2.3.4" and deploy to the "Development" environment

### Action

This prompt should create a new release and optionally deploy it to an environment.

The initial version should select the default value of any packages and prompted variables.

**Comment by harrisonmeister** [comment]
This has now been released.
