### ISSUE TITLE
Deploy a release

### ISSUE THREAD

**Issue by mcasperson** [OctopusSolutionsEngineering/OctopusCopilot#7]
### Chat query

Deploy release version "1.2.3" of project "My Project" to the environment "Production"

### Action

This prompt should deploy (or redeploy) an existing release to a new environment.

**Comment by harrisonmeister** [comment]
This has now been released. Note: it doesn't currently support deploying the latest deployment. You have to specify a release version you wish to deploy in the prompt. This may be added in a future release
