### ISSUE TITLE
Cancel a task / deployment / runbook

### ISSUE THREAD

**Issue by BobJWalker** [OctopusSolutionsEngineering/OctopusCopilot#8]
### Chat query

- Cancel the latest deployment to test for project [project name] on space [space name]
- Cancel the latest runbook run in test for project [project name] on space [space name]
- Cancel the task [task id]

### Action

Cancel the running task

**Comment by harrisonmeister** [comment]
- Canceling deployments :heavy_check_mark: 
- Canceling runbooks :heavy_check_mark: 
- Canceling task by id :heavy_check_mark: 


Note: runbook cancelation doesnt currently support the notion of "latest" runbook run. Instead the runbook name should be supplied e.g.

> @octopus-ai-app Cancel the runbook run "Apply Windows updates" in the project "My project" in the space "Default" in the "Development" environment
